# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caesar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainmodule',
            name='predict',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='brainmodule',
            name='result',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='brainmodule',
            name='trade_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
