# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caesar', '0003_brainmodule_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('precision', models.PositiveIntegerField(default=0)),
                ('recall', models.PositiveIntegerField(default=0)),
                ('disturb', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
