# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caesar', '0004_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quota',
            name='disturb',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quota',
            name='precision',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quota',
            name='recall',
            field=models.FloatField(default=0),
        ),
    ]
